collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: 10.4.0
    source: https://galaxy.ansible.com
  # Install a collection from Ansible Galaxy.
  - name: ansible.posix
    version: 2.0.0
    source: https://galaxy.ansible.com